# Vita

My vita is in this repository ([dlebauer-full-vita.pdf](https://github.com/dlebauer/vita/raw/master/dlebauer-full-vita.pdf)), but the primary purpose of this repository is to manage the content and the R code to automatically build my academic CV. The R package is based on the idea that content and style should be separate and that a person might want different CVs for different purposes. 

This repository is a fork from [James Keirstead](https://github.com/jkeirstead) who in turn credits [Kieran Healy](https://github.com/kjhealy/kjh-vita) and [Rob Hyndman](http://robjhyndman.com/research/cv.sty) for formatting and the use of Bibtex, respectively.
## Project layout

The project consists of:

 * a `content` directory that contains: YAML files for the overall CV
   configuration, YAML files to store the data for all of the
   non-publication parts of the CV, and a bibtex file that contains
   the publications.
   
 * a `style` directory that contains the overall LaTeX style, as well
   as scripts for inserting version control information
   

## Dependencies

* latex, latexmk, xelatex
* R

```sh
apt-get update
apt-get install texlive-xelatex latexmk fonts-font-awesome texlive-bibtex-extra biber
```

## Install

```{r eval = FALSE}
library(devtools)
install_github("dlebauer/vita")
```

## How to build a CV

Creating a new CV is relatively simple.

1) Export all of your publications as a `*.bib` file 

2) Write all of the other sections of your CV, putting them in YAML files

3) Write an overall CV file in YAML.  There are a couple of gotchas to
   be careful of here.
     
   * In the `publications` section, each of the named sections must
     correspond to a declared biblatex section in the style file,
     e.g. `jk-vita.sty`.
	   
   * In the `sections` section, the file field should contain the
     name of a YAML file describing that section's content.  **There
     must be a corresponding `format_{section}` function in the
     `{style}_functions.r` file that specifies how to display the
     information.** For example, if you have a section file called
     `awards.yaml` and you wish to generate a `tex` output document,
     then the `tex_functions.r` file must contain a `format_awards`
     function.

4) Define a style file.  At the moment, only LaTeX formats are
   supported so modify the `jk-vita.sty` file as appropriate.  The
   most important lines in here have to do with the formatting of the
   publications using biblatex, but there are also settings for fonts,
   colours, and other details.
   
5) Build the CV.  This is easy.  Simply open up the terminal, change to the
   repository directory, and run the following command:


```sh
./write_cv.R
```

Although the output goes in `/output` I also check in an up to date version of my CV in the root direcotry ([dlebauer-full-vita.pdf](https://github.com/dlebauer/vita/raw/master/dlebauer-full-vita.pdf)). 
