service:
  - context: Academic
    roles:
      - start: 2015
        end: 2016
        title: Reviewer
        entity: EarthCube Architecture Conceptual Design
      - start: 2012
        end: present
        title: Campus Representative
        entity: National Ecological Observatory Network (NEON)
      - start: 2009
        end: 2011
        title: Expert for Climate Science Experts Referal Service
        entity: American Geophysical Union
      - start: 2006
        end: 2008
        title: Judge
        entity: California State Science Fair
      - start: 2006
        end: 2007
        title: Graduate Student Representative
        entity: UCI Department of Earth System Science
      - start: 2005
        end: 2006
        title: Graduate Student Seminar Organizer
        entity: UCI Department of Earth System Science
      - start: 2003
        title: Project Mentor
        entity: FARMS Leadership, Inc. and Sacramento Public Schools
      - start: 1998
        end: 1999
        title: Guest Teacher, K-12
        entity: Sigma Xi, Scientists in the Classroom
  - context: Workshops
    roles:
      - date: March 2014
        role: Workshop Chair and Co-Organizer
        title: Advancing Software for Ecological Forecasting
        location: Urbana, IL
        website: http://conferences.igb.illinois.edu/ecological_forecasting/
      - date: August 2014
        role: Symposium Co-Organizer
        title: Challenges and Advances in Statistical Software For Ecology.
        location: Ecological Society of America Annual Meetings, Sacramento, CA
        website: http://eco.confex.com/eco/2014/webprogram/Session9692.html
      - date: November 2014
        role: Workshop Co-Organizer
        title: Soil Carbon Cycle Super-Modeling
        location: Biosphere 2, Oracle, AZ
        website: http://soil-metamodel.github.io/
  - context: Grant Reviews
    roles:
      - role: US National Science Foundation
  - context: Journal Reviewer
    roles:
    - role: Applied Soil Ecology
    - role: Ecology
    - role: Ecology Letters
    - role: Ecological Applications
    - role: Global Change Biology
    - role: Global Change Biology - Bioenergy
    - role: Geophysical Research Letters
    - role: Nature Climate Change
    - role: New Phytologist
    - role: Plant Soil
  - context: Consultancy
    roles:
      - role: "Agrible, Inc., Urbana, IL"
        start: 2015
      - role: "Smithsonian Institution, CTFS -- ForestGEO Ecosystems and Climate Initiative, Falls Curch, Va"
        start: 2015
      - role: "Global Change Solutions, LLC, Urbana, IL"
        start: 2011
        end: 2014
      - role: Wildflower Organics, Dawsonville, GA
        start: 1999
        end: 2000
      - role: Crabtree Valley Farms, Chatanooga, TN
        start: 2000
      - role: Sustenance Farm, Bear Creek, NC
        start: 1999

## Log of Reviews (incomplete)
## APSOIL
# APSOIL-D-09-00091R1
# APSOIL-D-09-00379
# APSOIL-D-11-00166
# APSOIL-D-12-00268R1
## https://mail.google.com/mail/ca/u/0/#search/Thank+you+for+the+review+of+APSOIL
## Ecology
# 07-1104
# 08-0792
# 09-0935
# 10-1558
# 11-1398
# https://mail.google.com/mail/ca/u/0/#search/#22Review+Received+by+Ecology#22
## GRL
# #2008GL033983
## New Phytologist
# NPH-MS-2012-14400
