service:
  - context: Academic
    roles:
      - start: 2021
        end: present
        title: Co-organizer
        entity: University of Arizona Drone Day \\url{drones.arizona.edu/ua-drone-day-2022}
      - start: 2021
        end: present
        title: Organizing Committee
        entity: North American Plant Phenotyping Network Conference
      - start: 2020
        end: present
        title: Member
        entity: Data Science Resources and Training Steering Committee
      - start: 2017
        end: present
        title: Google Summer of Code Mentor
        entity: PEcAn Project
      - start: 2015
        end: present
        title: Undergraduate Student Mentor
        entity: Students Pushing Innovation Program, National Center For Supercomputing Applications
      - start: 2015
        end: 2016
        title: Reviewer
        entity: EarthCube Architecture Conceptual Design
      - start: 2014
        end: 2016
        title: Graduate Student Summer Intern Mentor
        entity: Program for Interdisciplinary and Industrial Internships at Illinois
      - start: 2012
        end: 2016
        title: Campus Representative
        entity: National Ecological Observatory Network (NEON)
      - start: 2009
        end: 2011
        title: Expert for Climate Science Experts Referal Service
        entity: American Geophysical Union
      - start: 2006
        end: 2008
        title: Judge
        entity: California State Science Fair
      - start: 2006
        end: 2007
        title: Graduate Student Representative
        entity: UCI Department of Earth System Science
      - start: 2005
        end: 2006
        title: Graduate Student Seminar Organizer
        entity: UCI Department of Earth System Science
      - start: 2003
        title: Project Mentor
        entity: FARMS Leadership, Inc. and Sacramento Public Schools
      - start: 1998
        end: 1999
        title: Guest Teacher, K-12
        entity: Sigma Xi, Scientists in the Classroom
  - context: Workshops
    roles:
      - date: February 2019
        role: Organizer
        title: PEcAn+CLM Coupling and Beyond Workshop and Hackathon
        location: Santa Rita Experimental Range, Green Valley, Arizona
        website: https://sites.google.com/email.arizona.edu/pecan2019hack/home
      - date: February 2018
        role: Co-organizer
        title: "Big Data Driven Agriculture: Advances, Challenges, and Opportunities"
        location: USDA NIFA-FACT, Alexandria, VA
        website: https://www.datadrivenag.org/
      - date: November 2017
        role: Invited participant
        title: "The Subterranean Macroscope: Sensor Networks for Understanding, Modeling, and Managing Soil Processes"
        location: NSF, Chicago, IL
      - date: February 2017
        role: Co-organizer, lead instructor
        title: "Using TERRA REF phenotyping data"
        location: Phenome 2017, Tucson, AZ
      - date: February 2017
        role: Co-organizer
        title: "Phenome 2017 post-conference hackathon"
        location: University of Arizona, Tucson, AZ
      - date: January 2017
        role: Invited Participant
        title: "Moving Field Phenomics From Theory to Practice"
        location: US-UK Phenomics Workshop, Maricopa, AZ
      - date: October 2016
        role: Invited Participant
        title: "Plant Science Cyberinfrastructure Initiative"
        location: Plant Science Research Network, Washington, DC
      - date: August 2016
        role: Session Co-Organizer
        title: "Hacking Ecology 2.0, a showcase of open tools for data-driven ecology"
        location: Ecological Society of America Annual Meetings, Fort Lauderdale, FL
        website: https://sites.google.com/email.arizona.edu/pecan2019hack/home
      - date: November 2014
        role: Workshop Co-Organizer
        title: Soil Carbon Cycle Super-Modeling
        location: Biosphere 2, Oracle, AZ
        website: http://soil-metamodel.github.io/
      - date: August 2014
        role: Symposium Co-Organizer
        title: Challenges and Advances in Statistical Software For Ecology.
        location: Ecological Society of America Annual Meetings, Sacramento, CA
        website: http://eco.confex.com/eco/2014/webprogram/Session9692.html
      - date: March 2014
        role: Workshop Chair and Co-Organizer
        title: Advancing Software for Ecological Forecasting
        location: Urbana, IL
        website: https://www.slideshare.net/dlebauer/agenda-33017953
  - context: Grant Reviews
    roles:
      - role: United States Department of Agriculture
      - role: US National Science Foundation
      - role: Foundation for Food and Agricultural Research
  - context: Journal Reviewer
    roles:
    - role: Applied Soil Ecology
    - role: Ecology
    - role: Ecology Letters
    - role: Ecological Applications
    - role: Frontiers in Plant Science (Review Editor)
    - role: Global Change Biology
    - role: Global Change Biology - Bioenergy
    - role: Geophysical Research Letters
    - role: Global Ecology and Biogeography
    - role: Journal of Geophysical Research
    - role: Journal of Geophysical Research - Biogeosciences
    - role: Nature Climate Change
    - role: Open Data Journal for Agricultural Research
    - role: Nature Scientific Reports
    - role: Plants, People, Planet
    - role: Proceedings of the National Academy of Sciences of the United States of America
    - role: New Phytologist
    - role: Plant Soil
  - context: Consultancy
    roles:
      - role: "Agrible, Inc., Champaign, Il" #Senior Scientific Advisor 
        start: 2015
        end: 2018
      - role: "Smithsonian Institution, CTFS -- ForestGEO Ecosystems and Climate Initiative, Falls Curch, Va"
        start: 2015
        end: 2016
      - role: "Global Change Solutions, LLC, Urbana, IL"
        start: 2011
        end: 2014
      - role: Wildflower Organics, Dawsonville, GA
        start: 1999
        end: 2000
      - role: Crabtree Valley Farms, Chatanooga, TN
        start: 2000
      - role: Sustenance Farm, Bear Creek, NC
        start: 1999

## Log of Reviews (incomplete)
# PNAS
# Plant Phenomics
## APSOIL
# APSOIL-D-09-00091R1
# APSOIL-D-09-00379
# APSOIL-D-11-00166
# APSOIL-D-12-00268R1
## https://mail.google.com/mail/ca/u/0/#search/Thank+you+for+the+review+of+APSOIL
## Ecology
# 07-1104
# 08-0792
# 09-0935
# 10-1558
# 11-1398
# https://mail.google.com/mail/ca/u/0/#search/#22Review+Received+by+Ecology#22
## GRL
# #2008GL033983
## New Phytologist
# NPH-MS-2012-14400
## Global Change Biology 
# GCB-17-1694
