service:
    - start: 2012
      end: present
      role: Campus Representative
      entity: National Ecological Observatory Network (NEON)
#     - start: 2014
#       role: Steering group member
#       entity: Energy Research Partnership Cities project
    # - start: 2014
    #   role: Programme committee member
    #   entity: First International Workshop on Demand Response (DR2014).
    # - start: 2013
    #   role: Invited participant
    #   entity: EPSRC Engineering Leaders of the Future. October, Hellidon Lakes.
    # - start: 2013
    #   role: Invited participant
    #   entity: Research Councils UK energy strategy workshop on energy infrastructure.  Birmingham.
    # - start: 2013
    #   role: Technical committee member
    #   entity: International Society for Industrial Ecology conference
    # - start: 2015
    #   role: Technical committee member
    #   entity: International Society for Industrial Ecology conference
    # - start: 2011
    #   end: present
    #   role: Board member
    #   entity: Sustainable Urban Systems section, International Society for Industrial Ecology.
    # - start: 2011
    #   end: 2012
    #   role: Technical advisory panel member
    #   entity: Challenging Lock-in Through Urban Energy Systems EPRSC project
    # - start: 2011
    #   end: 2012
    #   role: Technical committee member
    #   entity: CIBSE ASHRAE Technical Symposium      
    # - start: 2011
    #   end: 2013
    #   role: Programme committee member
    #   entity: 2nd--4th International Workshops on Agent Technologies for Energy Systems (ATES)
    # - start: 2010
    #   role: Reviewer
    #   entity: ECOS and Next Generation Infrastructures conferences
    # - start: 2009
    #   role: Invited participant
    #   entity: EPSRC Grand Challenge workshop on Sustainable Urban Environments
grant_reviews:
  - US National Science Foundation
journal_reviews:
  - Applied Soil Ecology
  - Ecology
  - Ecology Letters               
  - Ecological Applications  
  - Global Change Biology
  - Global Change Biology - Bioenergy
  - Geophysical Research Letters
  - Nature Climate Change
  - New Phytologist
  - Plant Soil
consultancy:
  - Global Change Solutions, LLC
  - British Petroleum Lignocellulosic Biofuels
